function figure1 = plot_heatmap(data,filename)
%CREATEFIGURE(CDATA1)
%  CDATA1:  image cdata
%  CDATA2:  figure title data

%  Auto-generated by MATLAB on 20-Nov-2018 15:53:23

% Create figure
figure1 = figure;
colormap(jet);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create image
image(data,'Parent',axes1,'CDataMapping','scaled');

% Create xlabel
xlabel({'Time Relative to Transition (seconds)'});

% Create title
title({filename},'FontSize',20);
clear(filename)
% Create ylabel
ylabel({'Individual Transitions dF/F (%)'},'FontSize',16);

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0.5 5120.5]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0.5 (size(data,1)+.5)]);
box(axes1,'on');
axis(axes1,'ij');
% Set the remaining axes properties
set(axes1,'CLim',[-0.085941 0.15033],'FontSize',14,'Layer','top',...
    'TickLabelInterpreter','none','XTick',...
    [0.5 512.5 1024.5 1536.5 2048.5 2560.5 3072.5 3584.5 4096.5 4608.5 5120.5],...
    'XTickLabel',{'-10','','','','','0','','','','','10'},'YTick',[1 2 3 4],...
    'YTickLabel',{'','','',''});
% Create line
annotation(figure1,'line',[0.518064076346285 0.518064076346285],...
    [0.92722371967655 0.111859838274933],'Color',[1 1 1],'LineWidth',2,...
    'LineStyle','--');



